name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.7.6
          - 3.0.4
          - 3.1.2

        gemfile:
          - rails_5.2.gemfile
          - rails_6.0.gemfile
          - rails_6.1.gemfile
          - rails_7.0.gemfile

        exclude:
          - gemfile: rails_5.2.gemfile
            ruby: 3.0.4

          - gemfile: rails_5.2.gemfile
            ruby: 3.1.2

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and test with Rake
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          COVERAGE: true
        with:
          coverageCommand: bundle exec rspec
