name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x

        gemfile:
          - rails_5.1.gemfile
          - rails_5.2.gemfile
          - rails_6.0.gemfile

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Code Climate test-reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Build and test with Rake
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          COVERAGE=true bundle exec rspec
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

      - name: Upload coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          GIT_BRANCH=$(echo $GITHUB_REF | sed -e 's|.*/||') ./cc-test-reporter after-build
