name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x

        gemfile:
          - rails_5.1.gemfile
          - rails_5.2.gemfile

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and test with Rake
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
